$(document).ready(function() {
  // Block#: 1C:`578mBXF1!4X_u2|.
  function on_start() {
    try {
      // Block#: mN12,~pg:G?NM1ptu*FD
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", (com.fc.JavaScriptDistLib.TextLib.convertToText('')));
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  com.fc.JavaScriptDistLib.Application.registerEvent('start', on_start);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 272078-958244-907590-280161
